title: Benjamin Vial
description: Posdoctoral Research Asssistant | Optics, Photonics and microwave engineering
owner: Benjamin Vial
github_username: benvial
arxiv_username: Vial%2C+B
google_scholar_username: 2Z7zJqYAAAAJ
researchgate_username: Benjamin_Vial
linkedin_username: benjamin-vial-701018b9
year: 2020
