
# Site settings
title: Benjamin Vial
description: Posdoctoral Research Asssistant | Optics, Photonics and microwave engineering
# url: "http://webspace.qmul.ac.uk/bvial/"
# url: ""
owner: Benjamin Vial
# Secondary Parameters
# baseurl: "http://webspace.qmul.ac.uk/bvial"
# baseurl: ""
# logo: ./img/moi_round_4.png
# Tertiary Parameters
github_username: benvial
arxiv_username: Vial%2C+B
google_scholar_username: 2Z7zJqYAAAAJ
researchgate_username: Benjamin_Vial
linkedin_username: benjamin-vial-701018b9
year: 2019
