title: Benjamin Vial
description: Postdoctoral Research Asssistant | Optics, Photonics and Microwave Engineering
owner: Benjamin Vial
github_username: benvial
gitlab_username: benvial
arxiv_username: Vial%2C+B
google_scholar_username: 2Z7zJqYAAAAJ
researchgate_username: Benjamin_Vial
linkedin_username: benjamin-vial-701018b9
year: 2021
